package me.skorrloregaming;

import org.bukkit.Material;

import java.util.Arrays;
import java.util.List;

public class Directory {
	public static final int INVENTORY_SIZE = 41;
	public static List<Material> repairableArmor = Arrays.asList(new Material[] { Material.LEATHER_HELMET, Material.LEATHER_CHESTPLATE, Material.LEATHER_LEGGINGS, Material.LEATHER_BOOTS, Material.CHAINMAIL_HELMET, Material.CHAINMAIL_CHESTPLATE, Material.CHAINMAIL_LEGGINGS, Material.CHAINMAIL_BOOTS, Material.IRON_HELMET, Material.IRON_CHESTPLATE, Material.IRON_LEGGINGS, Material.IRON_BOOTS, Material.GOLDEN_HELMET, Material.GOLDEN_CHESTPLATE, Material.GOLDEN_LEGGINGS, Material.GOLDEN_BOOTS, Material.DIAMOND_HELMET, Material.DIAMOND_CHESTPLATE, Material.DIAMOND_LEGGINGS, Material.DIAMOND_BOOTS });
	public static List<Material> repairableItems = Arrays.asList(new Material[] { Material.WOODEN_SWORD, Material.WOODEN_PICKAXE, Material.WOODEN_AXE, Material.WOODEN_SHOVEL, Material.STONE_SWORD, Material.STONE_PICKAXE, Material.STONE_AXE, Material.STONE_SHOVEL, Material.IRON_SWORD, Material.IRON_PICKAXE, Material.IRON_AXE, Material.IRON_SHOVEL, Material.GOLDEN_SWORD, Material.GOLDEN_PICKAXE, Material.GOLDEN_AXE, Material.GOLDEN_SHOVEL, Material.DIAMOND_SWORD, Material.DIAMOND_PICKAXE, Material.DIAMOND_AXE, Material.DIAMOND_SHOVEL, Material.BOW, Material.ELYTRA });
	public static List<Material> swords = Arrays.asList(new Material[] { Material.WOODEN_SWORD, Material.STONE_SWORD, Material.IRON_SWORD, Material.GOLDEN_SWORD, Material.DIAMOND_SWORD });
	public static List<Material> pickaxes = Arrays.asList(new Material[] { Material.WOODEN_PICKAXE, Material.STONE_PICKAXE, Material.IRON_PICKAXE, Material.GOLDEN_PICKAXE, Material.DIAMOND_PICKAXE });
	public static List<Material> axes = Arrays.asList(new Material[] { Material.WOODEN_AXE, Material.STONE_AXE, Material.IRON_AXE, Material.GOLDEN_AXE, Material.DIAMOND_AXE });
	public static List<Material> spades = Arrays.asList(new Material[] { Material.WOODEN_SHOVEL, Material.STONE_SHOVEL, Material.IRON_SHOVEL, Material.GOLDEN_SHOVEL, Material.DIAMOND_SHOVEL });
	public static List<Material> stairs = Arrays.asList(new Material[] { Material.ACACIA_STAIRS, Material.BIRCH_STAIRS, Material.BRICK_STAIRS, Material.COBBLESTONE_STAIRS, Material.DARK_OAK_STAIRS, Material.NETHER_BRICK_STAIRS, Material.PURPUR_STAIRS, Material.QUARTZ_STAIRS, Material.RED_SANDSTONE_STAIRS, Material.SANDSTONE_STAIRS, Material.STONE_BRICK_STAIRS, Material.SPRUCE_STAIRS, Material.OAK_STAIRS });
	public static List<Material> beds = Arrays.asList(new Material[] { Material.BLACK_BED, Material.BLUE_BED, Material.BROWN_BED, Material.CYAN_BED, Material.GRAY_BED, Material.GREEN_BED, Material.LIGHT_BLUE_BED, Material.LIGHT_GRAY_BED, Material.LIME_BED, Material.MAGENTA_BED, Material.ORANGE_BED, Material.PINK_BED, Material.PURPLE_BED, Material.RED_BED, Material.WHITE_BED, Material.YELLOW_BED });
	public static String[] basicWorldEditPermissions = new String[] {
			"worldedit.biome.info",
			"worldedit.biome.set",
			"worldedit.biome.list",
			"worldedit.clipboard.cut",
			"worldedit.clipboard.paste",
			"worldedit.clipboard.clear",
			"worldedit.clipboard.copy",
			"worldedit.clipboard.flip",
			"worldedit.clipboard.rotate",
			"worldedit.reload",
			"worldedit.help",
			"worldedit.fast",
			"worldedit.generation.cylinder",
			"worldedit.generation.sphere",
			"worldedit.generation.forest",
			"worldedit.generation.pumpkins",
			"worldedit.generation.pyramid",
			"worldedit.generation.shape",
			"worldedit.biome.set",
			"worldedit.history.undo",
			"worldedit.history.redo",
			"worldedit.history.clear",
			"worldedit.navigation.unstuck",
			"worldedit.navigation.ascend",
			"worldedit.navigation.descend",
			"worldedit.navigation.ceiling",
			"worldedit.navigation.thru.command",
			"worldedit.navigation.jumpto.command",
			"worldedit.navigation.up",
			"worldedit.region.hollow",
			"worldedit.region.line",
			"worldedit.region.curve",
			"worldedit.region.overlay",
			"worldedit.region.center",
			"worldedit.region.naturalize",
			"worldedit.region.walls",
			"worldedit.region.faces",
			"worldedit.region.smooth",
			"worldedit.region.move",
			"worldedit.regen",
			"worldedit.region.deform",
			"worldedit.region.forest",
			"worldedit.region.replace",
			"worldedit.region.stack",
			"worldedit.region.set",
			"worldedit.scripting.execute",
			"worldedit.selection.pos",
			"worldedit.selection.chunk",
			"worldedit.selection.pos",
			"worldedit.selection.hpos",
			"worldedit.selection.hpos",
			"worldedit.wand",
			"worldedit.wand.toggle",
			"worldedit.selection.contract",
			"worldedit.selection.outset",
			"worldedit.selection.inset",
			"worldedit.analysis.distr",
			"worldedit.analysis.count",
			"worldedit.selection.size",
			"worldedit.selection.expand",
			"worldedit.selection.shift",
			"worldedit.snapshots.restore",
			"worldedit.snapshots.restore",
			"worldedit.snapshots.list",
			"worldedit.snapshots.restore",
			"worldedit.snapshots.restore",
			"worldedit.snapshots.restore",
			"worldedit.superpickaxe",
			"worldedit.superpickaxe",
			"worldedit.superpickaxe.area",
			"worldedit.superpickaxe.recursive",
			"worldedit.tool.tree",
			"worldedit.tool.replacer",
			"worldedit.tool.data-cycler",
			"worldedit.tool.flood-fill",
			"worldedit.brush.sphere",
			"worldedit.brush.cylinder",
			"worldedit.brush.clipboard",
			"worldedit.brush.smooth",
			"worldedit.brush.ex",
			"worldedit.brush.gravity",
			"worldedit.brush.butcher",
			"worldedit.tool.deltree",
			"worldedit.tool.farwand",
			"worldedit.tool.lrbuild",
			"worldedit.tool.info",
			"worldedit.brush.options.material",
			"worldedit.brush.options.range",
			"worldedit.brush.options.size",
			"worldedit.brush.options.mask",
			"worldedit.tool.tree",
			"worldedit.tool.replacer",
			"worldedit.tool.data-cycler",
			"worldedit.tool.flood-fill",
			"worldedit.brush.sphere",
			"worldedit.brush.cylinder",
			"worldedit.brush.clipboard",
			"worldedit.brush.smooth",
			"worldedit.brush.ex",
			"worldedit.brush.gravity",
			"worldedit.brush.butcher",
			"worldedit.tool.deltree",
			"worldedit.tool.farwand",
			"worldedit.tool.lrbuild",
			"worldedit.tool.info",
			"worldedit.fill.recursive",
			"worldedit.drain",
			"worldedit.fixlava",
			"worldedit.fixwater",
			"worldedit.removeabove",
			"worldedit.removebelow",
			"worldedit.removenear",
			"worldedit.replacenear",
			"worldedit.snow",
			"worldedit.thaw",
			"worldedit.green",
			"worldedit.extinguish",
			"worldedit.butcher",
			"worldedit.remove",
			"worldedit.fill",
			"worldedit.help" };
}
